-- Copyright © 2026 SuitablyMysterious
-- Usage without permission is expressly forbidden

-- Generated by FMC page compiler. Do not edit manually.

local registry = {}
registry.reverse = {
    ["REF_NAV_DATA.airport_ident"] = {
        {
            field = "magnetic_variation",
            page = "REF_NAV_DATA",
            slot = "L5",
        },
        {
            field = "latitude",
            page = "REF_NAV_DATA",
            slot = "L3",
        },
        {
            field = "elevation",
            page = "REF_NAV_DATA",
            slot = "R4",
        },
        {
            field = "runway_ident",
            page = "REF_NAV_DATA",
            slot = "L1",
        },
        {
            field = "runway_length",
            page = "REF_NAV_DATA",
            slot = "R5",
        },
        {
            field = "longitude",
            page = "REF_NAV_DATA",
            slot = "R3",
        },
    },
    ["REF_NAV_DATA.runway_ident"] = {
        {
            field = "magnetic_variation",
            page = "REF_NAV_DATA",
            slot = "L5",
        },
        {
            field = "latitude",
            page = "REF_NAV_DATA",
            slot = "L3",
        },
        {
            field = "elevation",
            page = "REF_NAV_DATA",
            slot = "R4",
        },
        {
            field = "runway_length",
            page = "REF_NAV_DATA",
            slot = "R5",
        },
        {
            field = "longitude",
            page = "REF_NAV_DATA",
            slot = "R3",
        },
    },
}
registry.pageKeys = {
    "REF_NAV_DATA",
}

function registry.loadPages(loader)
    local pagesByKey = {}
    for i = 1, #registry.pageKeys do
        local key = registry.pageKeys[i]
        pagesByKey[key] = loader(key)
    end
    return pagesByKey
end

function registry.propagate(symbol, pagesByKey, context)
    local targets = registry.reverse[symbol] or {}
    for i = 1, #targets do
        local t = targets[i]
        local page = pagesByKey[t.page]
        if page and type(page.updateDependency) == "function" then
            page.updateDependency(symbol, context)
        end
    end
    return targets
end

return registry
