-- Copyright © 2026 SuitablyMysterious
-- Usage without permission is expressly forbidden

-- Generated by FMC page compiler. Do not edit manually.

local function a_find_localizer_for_airport(nav, airport_ident, runway_ident)
    if not nav or type(nav.loc) ~= "table" then
        return nil
    end

    local fallback = nil
    for _, entries in pairs(nav.loc) do
        for _, loc in ipairs(entries) do
            if loc.airport == airport_ident then
                if runway_ident and loc.runway == runway_ident then
                    return loc
                end
                if not fallback then
                    fallback = loc
                end
            end
        end
    end

    return fallback
end

local function a_get_nav_parser()
    if earth_nav_parser then
        return earth_nav_parser
    end
    if custom_module and custom_module.parsers then
        return custom_module.parsers.earth_nav
    end
    return nil
end

local function ensure_nav_ready(nav)
    if not nav then
        return false
    end

    if not nav.ready and type(nav.load) == "function" then
        nav.load()
    end

    if type(nav.update) == "function" then
        nav.update()
    end

    return nav.ready == true
end

local function find_elevation(airport_ident, runway_ident)
    if runway_ident and airport_ident == nil then
        return nil
    end

    local nav = a_get_nav_parser()
    if not ensure_nav_ready(nav) then
        return nil
    end

    if airport_ident then
        local loc = a_find_localizer_for_airport(nav, airport_ident, runway_ident)
        if loc and loc.elev then
            return loc.elev
        end
    end

    local navaid = nav.findNavaid and nav.findNavaid(airport_ident)
    return navaid and navaid.elev or nil
end

local function find_latitude(airport_ident, runway_ident)
    if runway_ident and airport_ident == nil then
        return nil
    end

    local nav = a_get_nav_parser()
    if not ensure_nav_ready(nav) then
        return nil
    end

    if airport_ident then
        local loc = a_find_localizer_for_airport(nav, airport_ident, runway_ident)
        if loc and loc.lat then
            return loc.lat
        end
    end

    local navaid = nav.findNavaid and nav.findNavaid(airport_ident)
    return navaid and navaid.lat or nil
end

local function find_longitude(airport_ident, runway_ident)
    if runway_ident and airport_ident == nil then
        return nil
    end

    local nav = a_get_nav_parser()
    if not ensure_nav_ready(nav) then
        return nil
    end

    if airport_ident then
        local loc = a_find_localizer_for_airport(nav, airport_ident, runway_ident)
        if loc and loc.lon then
            return loc.lon
        end
    end

    local navaid = nav.findNavaid and nav.findNavaid(airport_ident)
    return navaid and navaid.lon or nil
end

local function find_magnetic_variation(airport_ident)
    if airport_ident == nil then
        return nil
    end

    local nav = a_get_nav_parser()
    if not ensure_nav_ready(nav) then
        return nil
    end

    local loc = a_find_localizer_for_airport(nav, airport_ident, nil)
    if loc and loc.mag_front and loc.true_brg then
        local d = loc.true_brg - loc.mag_front
        while d > 180 do d = d - 360 end
        while d < -180 do d = d + 360 end
        return d
    end

    return nil
end

local function find_runway_length(airport_ident, runway_ident)
    if airport_ident == nil or runway_ident == nil then
        return nil
    end

    local nav = a_get_nav_parser()
    if not ensure_nav_ready(nav) then
        return nil
    end

    local loc = a_find_localizer_for_airport(nav, airport_ident, runway_ident)
    if loc and loc.range then
            -- earth_nav_parser has localizer range, not physical runway length.
            return nil
    end

    return nil
end

local mainTable = {}
mainTable.ready = true
mainTable.pageKey = "REF_NAV_DATA"
mainTable.title = "REF NAV DATA"
mainTable.fieldsBySlot = {
    L1 = {
        action = "none",
        command = "update",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
        },
        dependencyRaw = "airport_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
        },
        dependencySymbols = {
            "airport_ident",
        },
        fieldType = "input",
        identifier = "runway_ident",
        inputHint = "runway",
        label = "RUNWAY IDENT",
        placeholder = "-----",
        slot = "L1",
    },
    L2 = {
        action = "none",
        command = "update",
        dependencyRaw = "none",
        dependencyRpn = {
        },
        dependencySymbols = {
        },
        fieldType = "input",
        identifier = "airport_ident",
        inputHint = "ICAO",
        label = "AIRPORT IDENT",
        placeholder = "----",
        slot = "L2",
    },
    L3 = {
        action = "none",
        command = "find_latitude",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
            "REF_NAV_DATA.runway_ident",
        },
        dependencyRaw = "airport_ident AND runway_ident OR airport_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "id",
                value = "runway_ident",
            },
            {
                type = "op",
                value = "and",
            },
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "op",
                value = "or",
            },
        },
        dependencySymbols = {
            "airport_ident",
            "runway_ident",
        },
        fieldType = "output",
        identifier = "latitude",
        label = "LATITUDE",
        placeholder = "",
        slot = "L3",
    },
    L5 = {
        action = "none",
        command = "find_magnetic_variation",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
            "REF_NAV_DATA.runway_ident",
        },
        dependencyRaw = "airport_ident AND NOT runway_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "id",
                value = "runway_ident",
            },
            {
                type = "op",
                value = "not",
            },
            {
                type = "op",
                value = "and",
            },
        },
        dependencySymbols = {
            "airport_ident",
            "runway_ident",
        },
        fieldType = "output",
        identifier = "magnetic_variation",
        label = "MAG VAR",
        placeholder = "",
        slot = "L5",
    },
    L6 = {
        action = "none",
        command = "none",
        dependencyRaw = "none",
        dependencyRpn = {
        },
        dependencySymbols = {
        },
        fieldType = "link",
        identifier = "index",
        label = "INDEX",
        placeholder = "<INDEX",
        slot = "L6",
    },
    R3 = {
        action = "none",
        command = "find_longitude",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
            "REF_NAV_DATA.runway_ident",
        },
        dependencyRaw = "airport_ident AND runway_ident OR airport_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "id",
                value = "runway_ident",
            },
            {
                type = "op",
                value = "and",
            },
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "op",
                value = "or",
            },
        },
        dependencySymbols = {
            "airport_ident",
            "runway_ident",
        },
        fieldType = "output",
        identifier = "longitude",
        label = "LONGITUDE",
        placeholder = "",
        slot = "R3",
    },
    R4 = {
        action = "none",
        command = "find_elevation",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
            "REF_NAV_DATA.runway_ident",
        },
        dependencyRaw = "airport_ident AND runway_ident OR airport_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "id",
                value = "runway_ident",
            },
            {
                type = "op",
                value = "and",
            },
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "op",
                value = "or",
            },
        },
        dependencySymbols = {
            "airport_ident",
            "runway_ident",
        },
        fieldType = "output",
        identifier = "elevation",
        label = "ELEVATION",
        placeholder = "",
        slot = "R4",
    },
    R5 = {
        action = "none",
        command = "find_runway_length",
        dependencyCanonical = {
            "REF_NAV_DATA.airport_ident",
            "REF_NAV_DATA.runway_ident",
        },
        dependencyRaw = "airport_ident AND runway_ident",
        dependencyRpn = {
            {
                type = "id",
                value = "airport_ident",
            },
            {
                type = "id",
                value = "runway_ident",
            },
            {
                type = "op",
                value = "and",
            },
        },
        dependencySymbols = {
            "airport_ident",
            "runway_ident",
        },
        fieldType = "output",
        identifier = "runway_length",
        label = "LENGTH",
        placeholder = "",
        slot = "R5",
    },
}
mainTable.reverseDeps = {
    ["REF_NAV_DATA.airport_ident"] = {
        {
            field = "magnetic_variation",
            slot = "L5",
        },
        {
            field = "latitude",
            slot = "L3",
        },
        {
            field = "elevation",
            slot = "R4",
        },
        {
            field = "runway_ident",
            slot = "L1",
        },
        {
            field = "runway_length",
            slot = "R5",
        },
        {
            field = "longitude",
            slot = "R3",
        },
    },
    ["REF_NAV_DATA.runway_ident"] = {
        {
            field = "magnetic_variation",
            slot = "L5",
        },
        {
            field = "latitude",
            slot = "L3",
        },
        {
            field = "elevation",
            slot = "R4",
        },
        {
            field = "runway_length",
            slot = "R5",
        },
        {
            field = "longitude",
            slot = "R3",
        },
    },
    airport_ident = {
        {
            field = "magnetic_variation",
            slot = "L5",
        },
        {
            field = "latitude",
            slot = "L3",
        },
        {
            field = "elevation",
            slot = "R4",
        },
        {
            field = "runway_ident",
            slot = "L1",
        },
        {
            field = "runway_length",
            slot = "R5",
        },
        {
            field = "longitude",
            slot = "R3",
        },
    },
    runway_ident = {
        {
            field = "magnetic_variation",
            slot = "L5",
        },
        {
            field = "latitude",
            slot = "L3",
        },
        {
            field = "elevation",
            slot = "R4",
        },
        {
            field = "runway_length",
            slot = "R5",
        },
        {
            field = "longitude",
            slot = "R3",
        },
    },
}

mainTable.commands = {
    ["find_magnetic_variation"] = find_magnetic_variation,
    ["find_latitude"] = find_latitude,
    ["find_elevation"] = find_elevation,
    ["find_runway_length"] = find_runway_length,
    ["find_longitude"] = find_longitude,
}

local function evalDependencyRpn(rpn, values)
    if not rpn or #rpn == 0 then
        return true
    end

    local stack = {}
    for i = 1, #rpn do
        local tok = rpn[i]
        if tok.type == "id" then
            stack[#stack + 1] = not not values[tok.value]
        elseif tok.type == "op" then
            if tok.value == "not" then
                local a = stack[#stack]
                stack[#stack] = not a
            else
                local b = stack[#stack]
                stack[#stack] = nil
                local a = stack[#stack]
                stack[#stack] = nil
                if tok.value == "and" then
                    stack[#stack + 1] = a and b
                else
                    stack[#stack + 1] = a or b
                end
            end
        end
    end

    return not not stack[1]
end

function mainTable.fieldVisible(slot, values)
    local field = mainTable.fieldsBySlot[slot]
    if not field then
        return false
    end
    values = values or {}
    return evalDependencyRpn(field.dependencyRpn, values)
end

function mainTable.runCommand(slot, ...)
    local field = mainTable.fieldsBySlot[slot]
    if not field then
        return nil, "Unknown slot"
    end

    local cmd = field.command
    if cmd == "" or cmd == "none" then
        return nil
    end
    if cmd == "update" then
        return true
    end

    local fn = mainTable.commands[cmd]
    if not fn then
        return nil, "Missing compiled command: " .. tostring(cmd)
    end

    return fn(...)
end

function mainTable.updateDependency(symbol, context)
    local targets = mainTable.reverseDeps[symbol] or {}
    if not context or type(context.recompute) ~= "function" then
        return targets
    end

    for i = 1, #targets do
        context.recompute(mainTable, targets[i], context)
    end
    return targets
end

return mainTable
